### ISSUE TITLE
Aligner might move additional first word to the end of the alignment

### ISSUE THREAD

**Issue by Ar770** [CAMeL-Lab/ced_word_alignment#2] opened 2023-07-27 19:15 UTC
Consider the following example:
gold = "نحن نعيش في عالم رقمي حيث تتراكم كمية هائلة من المعلومات عنا"
hypo = "نعم  نحن نعيش في عالم رقمي حيث تتراكم كمية هائلة من المعلومات عنا"

Will output:
SOURCE	TARGET
نحن	نحن
نعيش	نعيش
في	في
عالم	عالم
رقمي	رقمي
حيث	حيث
تتراكم	تتراكم
كمية	كمية
هائلة	هائلة
من	من
المعلومات	المعلومات
نعم  عنا	عنا

As you can see, the first word in hypo (نعم) was moved to the end of the alignment.
Thanks

**Comment by Ar770** [comment] 2023-07-27 19:26
I was just trying an English example and it worked as expected, maybe it is related to RTL languages, like Arabic and Hebrew.

**Comment by slkh** [comment] 2023-07-27 19:37
Can you provide an English example?
I highly doubt that this is an RTL issue since the script was tested on Arabic script. We will look into it.

Thanks for reporting the issue.

**Comment by Ar770** [comment] 2023-07-27 19:55
Translating this exact example:
gold = "We live in a digital world where a huge amount of information about us accumulates"
hypo = "Yes we live in a digital world where a huge amount of information about us accumulates"

Will output:
SOURCE	TARGET
Yes we	We
live	live
in	in
a	a
digital	digital
world	world
where	where
a	a
huge	huge
amount	amount
of	of
information	information
about	about
us	us
accumulates	accumulates

**Comment by owo** [comment] 2023-07-28 07:06
I have identified the source of the issue and will work on fixing it.

In the meantime, a temporary fix would be to add start-of-sentence and end-of-sentence tags in both source and target (it doesn't matter what they are).

For example:
```
// Gold
<s> نحن نعيش في عالم رقمي حيث تتراكم كمية هائلة من المعلومات عنا </s>

// Hypo
<s> نعم نحن نعيش في عالم رقمي حيث تتراكم كمية هائلة من المعلومات عنا </s>
```

**Comment by Ar770** [comment] 2023-07-28 07:12
Looking good,
Thanks.

**Comment by Ar770** [comment] 2023-07-30 13:35
@owo
> I have identified the source of the issue and will work on fixing it.
> 
> In the meantime, a temporary fix would be to add start-of-sentence and end-of-sentence tags in both source and target (it doesn't matter what they are).
> 
> For example:
> 
> ```
> // Gold
> <s> نحن نعيش في عالم رقمي حيث تتراكم كمية هائلة من المعلومات عنا </s>
> 
> // Hypo
> <s> نعم نحن نعيش في عالم رقمي حيث تتراكم كمية هائلة من المعلومات عنا </s>
> ``` 

For:
```
gold = '<s> חיים בעולם דיגיטלי שבו נצברת כמות עצומה של מידע לגבינו </s>'
hypo = '<s> כן חיים בעולם דיגיטלי שבו נצברת כמות עצומה של מידע לגבינו </s>'
```
I get:
```
SOURCE	TARGET
<s> כן	<s>
חיים	חיים
בעולם	בעולם
דיגיטלי	דיגיטלי
שבו	שבו
נצברת	נצברת
כמות	כמות
עצומה	עצומה
של	של
מידע	מידע
לגבינו	לגבינו
</s>	</s>

```

**Comment by owo** [comment] 2023-08-09 17:14
The issue is now fixed. You'll need to reinstall the dependencies though.

**Closed as completed by owo** 2023-08-09 17:14 UTC
